apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  ports:
  - port: {{ .Values.service.rabbitmq.http.port }}
    name: http
  selector:
    app: rabbitmq
  type: {{ .Values.service.rabbitmq.http.type }}
