apiVersion: v1
kind: Service
metadata:
  name: firewall-ui-frontend-service
spec:
  selector:
    app: firewall-ui-frontend
    release: stable
  ports:
  - port: {{ .Values.service.firewall.frontend.port }}
    targetPort: 80
    protocol: TCP
