apiVersion: v1
kind: Service
metadata:
  name: celery-service
spec:
  selector:
    app: celery
  type: {{ .Values.service.celery.type }}
  ports:
  - port: {{ .Values.service.celery.port }}
    targetPort: 8080
    protocol: TCP
    nodePort: {{ .Values.service.celery.nodePort }}
