apiVersion: v1
kind: Service
metadata:
  name: uop-service
spec:
  selector:
    app: uop
  type: {{ .Values.service.uop.type }}
  ports:
  - port: {{ .Values.service.uop.port }}
    targetPort: 8080
    protocol: TCP
    nodePort: {{ .Values.service.uop.nodePort }}
