apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: {{ .Values.service.rabbitmq.amqp.port }}
    name: amqp
  - port: {{ .Values.service.rabbitmq.epmd.port }}
    name: epmd
  - port: {{ .Values.service.rabbitmq.rabbitmq_dist.port }}
    name: rabbitmq-dist
  clusterIP: {{ .Values.service.rabbitmq.clusterIP }}
  selector:
    app: rabbitmq
